/* Regenerates src/components/ui/icon-paths.js.
 *
 * The mobile app draws icons with react-native-vector-icons/FontAwesome (73 of
 * its 80 icon-using files; 6 use MaterialCommunityIcons, 1 uses Ionicons). To
 * make the web look the same, we ship the SAME FontAwesome glyphs — but as
 * inlined path data rather than a runtime dependency. Path data is data: no
 * version drift, no tree-shaking to get wrong, no font file to download.
 *
 * The FontAwesome packages are devDependencies used only by this script.
 *
 * Usage:  node scripts/extract-icons.mjs
 * Adding an icon: put the app's own name in NAMES (and an ALIASES entry if
 * FontAwesome spells it differently), then re-run.
 */

import * as solid from "@fortawesome/free-solid-svg-icons";
import * as brands from "@fortawesome/free-brands-svg-icons";
import { writeFileSync } from "node:fs";

/* Every icon name the app actually uses today, harvested from
   CrewApply/src/{components,screens,navigation}. Keys in the generated file are
   these app-side names, so a component ported from the app keeps name="email"
   and does not need rewriting. */
const NAMES = `
arrow-left arrow-right bars bell bell-slash bookmark briefcase calendar-alt calendar-check
calendar-times camera certificate check check-circle chevron-down chevron-left chevron-right
cloud-download-alt cog copy download education ellipsis-h ellipsis-v email exchange-alt
exclamation-circle exclamation-triangle eye eye-slash file-alt file-document-outline
folder-open gem genderless globe graduation-cap help-circle hourglass-half id-card image
info-circle lightbulb link location-arrow lock magic map-marker-alt mars paper-plane
pencil-alt phone-alt plus route search share-alt ship shopping-bag sign-out-alt sliders-h
sync-alt tag times times-circle trash-alt upload user user-circle user-friends venus wallet
whatsapp
`.split(/\s+/).filter(Boolean);

/* App-side name → FontAwesome name, for the few the app borrows from
   MaterialCommunityIcons or spells differently. */
const ALIASES = {
  education: "graduation-cap",
  email: "envelope",
  "help-circle": "question-circle",
  "file-document-outline": "file-alt",
};

const camel = (n) =>
  "fa" + n.split("-").map((p) => p[0].toUpperCase() + p.slice(1)).join("");

const out = {};
const missing = [];

for (const name of NAMES) {
  const def = solid[camel(ALIASES[name] ?? name)] || brands[camel(ALIASES[name] ?? name)];
  if (!def?.icon) {
    missing.push(name);
    continue;
  }
  const [width, height, , , path] = def.icon;
  out[name] = [width, height, Array.isArray(path) ? path.join(" ") : path];
}

const body = Object.entries(out)
  .map(([n, [w, h, d]]) => `  ${JSON.stringify(n)}: [${w}, ${h}, ${JSON.stringify(d)}],`)
  .join("\n");

writeFileSync(
  "src/components/ui/icon-paths.js",
  `/* GENERATED by scripts/extract-icons.mjs — do not edit by hand.
 *
 * FontAwesome Free path data for the ${Object.keys(out).length} icons the mobile app uses, so the web
 * draws the same glyphs the app does. Inlined rather than depended on at runtime.
 *
 * Icons: FontAwesome Free, CC BY 4.0 — https://fontawesome.com/license/free
 *
 * Shape: appIconName -> [viewBoxWidth, viewBoxHeight, path]. FontAwesome
 * viewBoxes differ per glyph, so the dimensions travel with each path.
 */
export const ICON_PATHS = {\n${body}\n};\n`,
);

console.log(`extracted ${Object.keys(out).length} icons`);
if (missing.length) console.log("MISSING:", missing.join(" "));
